---
- hosts: all
  user: ronald
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - common
    - virtualbox
    - terraform
  
  tasks:
  - name: Install various snap packages
    snap:
      name: "{{ item }}"
      classic: yes
    with_items:
      - code
      - intellij-idea-ultimate
      - goland
      - pycharm-professional
      - clion
      - go
      - docker
      - microk8s
      - helm

  - name: Snap does not update packages only checks existence, refresh with shell command
    shell: snap refresh

  - name: Post docker installation steps
    group:
      name: docker
      state: present

  - name: Add the user 'ronald' to the group of 'docker'
    user:
      name: ronald
      append: yes
      groups: docker

  - name: Add kubectl alias for microk8s kubectl
    lineinfile:
      path: /home/ronald/.zshrc
      line: "alias kubectl='microk8s kubectl'"
      regexp: "^alias kubectl='microk8s kubectl'"
      insertafter: EOF

  - name: Post microk8s installation steps
    group:
      name: microk8s
      state: present

  - name: Add the user 'ronald' to the group of 'microk8s'
    user:
      name: ronald
      append: yes
      groups: microk8s

  # TODO Azure CLI install doesn't work with Linux Mint Tricia
  # - name: Install Azure CLI
  #   shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  
  # Looks like snap/bin is not added to the path on remote ssh. Why? This is a quick fix
  - name: Add kubectl alias for microk8s kubectl
    lineinfile:
      path: /home/ronald/.zshrc
      line: 'export PATH="$PATH:/snap/bin"'
      regexp: '^export PATH="$PATH:/snap/bin"'
      insertafter: EOF

  - name: Add Vagrant
    apt:
      deb: https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb