---
- hosts: dev
  user: ronald
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - common
    - virtualbox
  
  tasks:
  - name: Install various snap packages
    snap:
      name: "{{ item }}"
      classic: yes
    with_items:
      - code
      - intellij-idea-ultimate
      - goland
      - pycharm-professional
      - clion
      - go
      - docker
      - kubectl

  - name: Post docker installation steps
    group:
      name: docker
      state: present

  - name: Add the user 'ronald' to the group of 'docker'
    user:
      name: ronald
      append: yes
      groups: docker

  # TODO Azure CLI install doesn't work with Linux Mint Tricia
  # - name: Install Azure CLI
  #   shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  