---
- hosts: dev
  user: ronald
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - common
    - virtualbox
  
  tasks:
  # Install developer IDE's
  - name: Install developer IDE's via snap
    snap:
      name: "{{ item }}"
      classic: yes
    with_items:
      - code
      - intellij-idea-ultimate
      - goland
      - pycharm-professional
      - clion

  # TODO 
  # - Install Golang
  # - openjdk 1.13
  # - docker
  # - zsh
  # - kubernetes
  # - Azure CLI
        