# Install virtual box
- name: Add VirtualBox repo key
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib
    state: present
    update_cache: yes

- name: Install virtualbox
  apt:
    name: virtualbox-6.1
    state: present

- name: Download VirtualBox extension pack
  get_url:
    url: "https://download.virtualbox.org/virtualbox/6.1.2/Oracle_VM_VirtualBox_Extension_Pack-6.1.2.vbox-extpack"
    dest: /tmp/
    force: yes

- name: Install virtual box extension pack
  shell: echo 'y' | vboxmanage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-6.1.2.vbox-extpack

- name: Add the user 'ronald' to the group of 'vboxusers'
  user:
    name: ronald
    append: yes
    groups: vboxusers
