# Install virtual box
- name: Add Hashicorp repo key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com bionic main
    state: present
    update_cache: yes

- name: Install terraform
  apt:
    name: terraform
    state: present
