# Install common linux packages
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install various generic packages
  apt:
    pkg:
    - git
    - ansible
    - terminator
    - snapd
    - python3-pip
    - zsh
    - iptables-persistent
    - openjdk-17-jdk
    - maven
    - jq
    - build-essential
#    - emu-kvm
#    - libvirt-daemon
#    - libvirt-daemon-system
#    - network-manager

- name: Install virtualenv
  pip:
    executable: pip3
    name: virtualenv    

# Create some default directories
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ronald
    group: ronald
    mode: 0755
  with_items:
    - /home/ronald/data/environments
    - /home/ronald/data/github/rmoetwil

#
# TODO This install only works the 1st time
#
# - name: Install Oh my Zsh
#   shell: echo Y | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
#   become: yes
#   become_user: ronald
