# Install common linux packages
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install various generic packages
  apt:
    pkg:
    - git
    - ansible
    - terminator
    - snapd